export default {
  INCORRECT_EMAIL_OR_PASSWORD: 'INCORRECT_EMAIL_OR_PASSWORD',
  USER_NOT_AUTHORIZED: 'USER_NOT_AUTHORIZED',
  USER_NOT_AUTHENTICATED: 'USER_NOT_AUTHENTICATED',

  ACCESS_FORBIDDEN: 'ACCESS_FORBIDDEN',

  ROLE_DOES_NOT_EXIST: 'ROLE_DOES_NOT_EXIST',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_VALUE_NOT_FOUND: 'ROLE_VALUE_NOT_FOUND',

  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USERS_NOT_FOUND: 'USERS_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
} as const;
