export default {
  ROLE_DOES_NOT_EXIST: 'ROLE_DOES_NOT_EXIST',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_VALUE_NOT_FOUND: 'ROLE_VALUE_NOT_FOUND',

  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USERS_NOT_FOUND: 'USERS_NOT_FOUND',
} as const;
